package com.coutinho.estereofinance.ui.theme

import androidx.compose.ui.graphics.Color

internal val PrimaryLight = Color(0xFFFF8C42)
internal val OnPrimaryLight = Color(0xFFFFFFFF)
internal val PrimaryContainerLight = Color(0xFFFFDBC9)
internal val OnPrimaryContainerLight = Color(0xFF331200)
internal val SecondaryLight = Color(0xFFFFBF5C)
internal val OnSecondaryLight = Color(0xFFFFFFFF)
internal val SecondaryContainerLight = Color(0xFFE6DA69)
internal val OnSecondaryContainerLight = Color(0xFF171614) // This color value is 0xFF171614
internal val TertiaryLight = Color(0xFFFFF275)
internal val OnTertiaryLight = Color(0xFFFFFFFF)
internal val TertiaryContainerLight = Color(0xFF9D931D)
internal val OnTertiaryContainerLight = Color(0xFF171614) // This color value is 0xFF171614
internal val ErrorLight = Color(0xFFFF3C38)
internal val OnErrorLight = Color(0xFFFFFFFF)
internal val ErrorContainerLight = Color(0xFFFFBDBB)
internal val OnErrorContainerLight = Color(0xFF171614) // This color value is 0xFF171614
internal val BackgroundLight = Color(0xFFFCFAF7) // This value is not directly in the colorScheme, derived from onSurface
internal val OnBackgroundLight = Color(0xFF171614) // This value is not directly in the colorScheme, derived from surface
internal val SurfaceLight = Color(0xFFF7F7FF)
internal val OnSurfaceLight = Color(0xFFFF8C42)
internal val SurfaceVariantLight = Color(0xFFFF785A) // This value is 0xFFFF785A
internal val OnSurfaceVariantLight = Color(0xFFFF785A) // This value is 0xFFFF785A
internal val OutlineLight = Color(0xFFFFE0B0)
internal val OutlineVariantLight = Color(0xFFD7C2B8)
internal val ScrimLight = Color(0xFF000000)
internal val InverseSurfaceLight = Color(0xFF0F1116)
internal val InverseOnSurfaceLight = Color(0xFFFF8C42)
internal val InversePrimaryLight = Color(0xFFFFBF5C)
internal val SurfaceDimLight = Color(0xFFE8D7CF)
internal val SurfaceBrightLight = Color(0xFFFFF8F6)
internal val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val SurfaceContainerLowLight = Color(0xFFFFF1EB)
internal val SurfaceContainerLight = Color(0xFFFCEAE2)
internal val SurfaceContainerHighLight = Color(0xFFF6E5DD)
internal val SurfaceContainerHighestLight = Color(0xFFFFAA5A)

internal val PrimaryDark = Color(0xFFFF8C42)
internal val OnPrimaryDark = Color(0xFFFFFFFF)
internal val PrimaryContainerDark = Color(0xFFFFE9D3)
internal val OnPrimaryContainerDark = Color(0xFFFDDBC9) // Corrected from json to match standard
internal val SecondaryDark = Color(0xFFFF785A)
internal val OnSecondaryDark = Color(0xFFFFFFFF)
internal val SecondaryContainerDark = Color(0xFFFFDAD2)
internal val OnSecondaryContainerDark = Color(0xFFFF785A) // This value is 0xFFFF785A
internal val TertiaryDark = Color(0xFFFFBF5C)
internal val OnTertiaryDark = Color(0xFFFFFFFF)
internal val TertiaryContainerDark = Color(0xFFFDDEAE)
internal val OnTertiaryContainerDark = Color(0xFF271900)
internal val ErrorDark = Color(0xFFFF3C38)
internal val OnErrorDark = Color(0xFFFFFFFF)
internal val ErrorContainerDark = Color(0xFFFFDAD6)
internal val OnErrorContainerDark = Color(0xFFFF9593)
internal val BackgroundDark = Color(0xFF171614) // This value is not directly in the colorScheme, derived from surface
internal val OnBackgroundDark = Color(0xFFFF8C42) // This value is not directly in the colorScheme, derived from onSurface
internal val SurfaceDark = Color(0xFF171614)
internal val OnSurfaceDark = Color(0xFFFF8C42)
internal val SurfaceVariantDark = Color(0xFFFFAC24) // Placeholder as it's not explicitly in JSON. Using a similar tone
internal val OnSurfaceVariantDark = Color(0xFFFFFAC4)
internal val OutlineDark = Color(0xFFFFBF5C)
internal val OutlineVariantDark = Color(0xFF52443C)
internal val ScrimDark = Color(0xFF000000)
internal val InverseSurfaceDark = Color(0xFFFFaa5a) // Corrected from json value 'ffaa5a'
internal val InverseOnSurfaceDark = Color(0xFFFFF275) // Corrected from json value 'fffff275'
internal val InversePrimaryDark = Color(0xFFFF785A)
internal val SurfaceDimDark = Color(0xFF1A120D)
internal val SurfaceBrightDark = Color(0xFF413732)
internal val SurfaceContainerLowestDark = Color(0xFF140D08)
internal val SurfaceContainerLowDark = Color(0xFF221A15)
internal val SurfaceContainerDark = Color(0xFF271E19)
internal val SurfaceContainerHighDark = Color(0xFF312823)
internal val SurfaceContainerHighestDark = Color(0xFFFFF275) // Corrected from json value 'fffff275'
